/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthUnauthorizedRouteImport } from './pages/_auth/unauthorized'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './pages/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AuthCheckEmailRouteImport } from './pages/_auth/check-email'
import { Route as AppDefinePasswordRouteImport } from './pages/_app/define-password'
import { Route as AppUserIndexRouteImport } from './pages/_app/user/index'
import { Route as AppProductIndexRouteImport } from './pages/_app/product/index'
import { Route as AppUserNewRouteImport } from './pages/_app/user/new'
import { Route as AppProductNewRouteImport } from './pages/_app/product/new'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppDefinePasswordRoute = AppDefinePasswordRouteImport.update({
  id: '/define-password',
  path: '/define-password',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductIndexRoute = AppProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUserNewRoute = AppUserNewRouteImport.update({
  id: '/user/new',
  path: '/user/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductNewRoute = AppProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/define-password': typeof AppDefinePasswordRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/product/new': typeof AppProductNewRoute
  '/user/new': typeof AppUserNewRoute
  '/product/': typeof AppProductIndexRoute
  '/user/': typeof AppUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/define-password': typeof AppDefinePasswordRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/product/new': typeof AppProductNewRoute
  '/user/new': typeof AppUserNewRoute
  '/product': typeof AppProductIndexRoute
  '/user': typeof AppUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/define-password': typeof AppDefinePasswordRoute
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/product/new': typeof AppProductNewRoute
  '/_app/user/new': typeof AppUserNewRoute
  '/_app/product/': typeof AppProductIndexRoute
  '/_app/user/': typeof AppUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/define-password'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/unauthorized'
    | '/product/new'
    | '/user/new'
    | '/product/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/define-password'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/unauthorized'
    | '/product/new'
    | '/user/new'
    | '/product'
    | '/user'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/define-password'
    | '/_auth/check-email'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/unauthorized'
    | '/_app/'
    | '/_app/product/new'
    | '/_app/user/new'
    | '/_app/product/'
    | '/_app/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/define-password': {
      id: '/_app/define-password'
      path: '/define-password'
      fullPath: '/define-password'
      preLoaderRoute: typeof AppDefinePasswordRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/user/': {
      id: '/_app/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product/': {
      id: '/_app/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof AppProductIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/user/new': {
      id: '/_app/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof AppUserNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product/new': {
      id: '/_app/product/new'
      path: '/product/new'
      fullPath: '/product/new'
      preLoaderRoute: typeof AppProductNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppDefinePasswordRoute: typeof AppDefinePasswordRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductNewRoute: typeof AppProductNewRoute
  AppUserNewRoute: typeof AppUserNewRoute
  AppProductIndexRoute: typeof AppProductIndexRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDefinePasswordRoute: AppDefinePasswordRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductNewRoute: AppProductNewRoute,
  AppUserNewRoute: AppUserNewRoute,
  AppProductIndexRoute: AppProductIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
