/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthUnauthorizedRouteImport } from './pages/_auth/unauthorized'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './pages/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AuthCheckEmailRouteImport } from './pages/_auth/check-email'
import { Route as AppDefinePasswordRouteImport } from './pages/_app/define-password'
import { Route as AppUserIndexRouteImport } from './pages/_app/user/index'
import { Route as AppUnitIndexRouteImport } from './pages/_app/unit/index'
import { Route as AppStockRequisitionIndexRouteImport } from './pages/_app/stock-requisition/index'
import { Route as AppStockLocationIndexRouteImport } from './pages/_app/stock-location/index'
import { Route as AppPurchaseIndexRouteImport } from './pages/_app/purchase/index'
import { Route as AppProductIndexRouteImport } from './pages/_app/product/index'
import { Route as AppProductBrandIndexRouteImport } from './pages/_app/product-brand/index'
import { Route as AppDepartmentIndexRouteImport } from './pages/_app/department/index'
import { Route as AppCategoryIndexRouteImport } from './pages/_app/category/index'
import { Route as AppUserNewRouteImport } from './pages/_app/user/new'
import { Route as AppUserEditRouteImport } from './pages/_app/user/edit'
import { Route as AppPurchaseNewRouteImport } from './pages/_app/purchase/new'
import { Route as AppPurchaseEditRouteImport } from './pages/_app/purchase/edit'
import { Route as AppProductBrandNewRouteImport } from './pages/_app/product-brand/new'
import { Route as AppProductBrandEditRouteImport } from './pages/_app/product-brand/edit'
import { Route as AppDepartmentNewRouteImport } from './pages/_app/department/new'
import { Route as AppDepartmentEditRouteImport } from './pages/_app/department/edit'
import { Route as AppCategoryNewRouteImport } from './pages/_app/category/new'
import { Route as AppCategoryEditRouteImport } from './pages/_app/category/edit'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppDefinePasswordRoute = AppDefinePasswordRouteImport.update({
  id: '/define-password',
  path: '/define-password',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUnitIndexRoute = AppUnitIndexRouteImport.update({
  id: '/unit/',
  path: '/unit/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppStockRequisitionIndexRoute =
  AppStockRequisitionIndexRouteImport.update({
    id: '/stock-requisition/',
    path: '/stock-requisition/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppStockLocationIndexRoute = AppStockLocationIndexRouteImport.update({
  id: '/stock-location/',
  path: '/stock-location/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPurchaseIndexRoute = AppPurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductIndexRoute = AppProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductBrandIndexRoute = AppProductBrandIndexRouteImport.update({
  id: '/product-brand/',
  path: '/product-brand/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDepartmentIndexRoute = AppDepartmentIndexRouteImport.update({
  id: '/department/',
  path: '/department/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCategoryIndexRoute = AppCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUserNewRoute = AppUserNewRouteImport.update({
  id: '/user/new',
  path: '/user/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUserEditRoute = AppUserEditRouteImport.update({
  id: '/user/edit',
  path: '/user/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUnitNewRoute = AppUnitNewRouteImport.update({
  id: '/unit/new',
  path: '/unit/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppUnitEditRoute = AppUnitEditRouteImport.update({
  id: '/unit/edit',
  path: '/unit/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppStockRequisitionNewRoute = AppStockRequisitionNewRouteImport.update({
  id: '/stock-requisition/new',
  path: '/stock-requisition/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppStockRequisitionEditRoute = AppStockRequisitionEditRouteImport.update({
  id: '/stock-requisition/edit',
  path: '/stock-requisition/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppStockLocationNewRoute = AppStockLocationNewRouteImport.update({
  id: '/stock-location/new',
  path: '/stock-location/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppStockLocationEditRoute = AppStockLocationEditRouteImport.update({
  id: '/stock-location/edit',
  path: '/stock-location/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPurchaseNewRoute = AppPurchaseNewRouteImport.update({
  id: '/purchase/new',
  path: '/purchase/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPurchaseEditRoute = AppPurchaseEditRouteImport.update({
  id: '/purchase/edit',
  path: '/purchase/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductBrandNewRoute = AppProductBrandNewRouteImport.update({
  id: '/product-brand/new',
  path: '/product-brand/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProductBrandEditRoute = AppProductBrandEditRouteImport.update({
  id: '/product-brand/edit',
  path: '/product-brand/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDepartmentNewRoute = AppDepartmentNewRouteImport.update({
  id: '/department/new',
  path: '/department/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDepartmentEditRoute = AppDepartmentEditRouteImport.update({
  id: '/department/edit',
  path: '/department/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCategoryNewRoute = AppCategoryNewRouteImport.update({
  id: '/category/new',
  path: '/category/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCategoryEditRoute = AppCategoryEditRouteImport.update({
  id: '/category/edit',
  path: '/category/edit',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/define-password': typeof AppDefinePasswordRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/category/edit': typeof AppCategoryEditRoute
  '/category/new': typeof AppCategoryNewRoute
  '/department/edit': typeof AppDepartmentEditRoute
  '/department/new': typeof AppDepartmentNewRoute
  '/product-brand/edit': typeof AppProductBrandEditRoute
  '/product-brand/new': typeof AppProductBrandNewRoute
  '/purchase/edit': typeof AppPurchaseEditRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/stock-location/edit': typeof AppStockLocationEditRoute
  '/stock-location/new': typeof AppStockLocationNewRoute
  '/stock-requisition/edit': typeof AppStockRequisitionEditRoute
  '/stock-requisition/new': typeof AppStockRequisitionNewRoute
  '/unit/edit': typeof AppUnitEditRoute
  '/unit/new': typeof AppUnitNewRoute
  '/user/edit': typeof AppUserEditRoute
  '/user/new': typeof AppUserNewRoute
  '/category/': typeof AppCategoryIndexRoute
  '/department/': typeof AppDepartmentIndexRoute
  '/product-brand/': typeof AppProductBrandIndexRoute
  '/product/': typeof AppProductIndexRoute
  '/purchase/': typeof AppPurchaseIndexRoute
  '/stock-location/': typeof AppStockLocationIndexRoute
  '/stock-requisition/': typeof AppStockRequisitionIndexRoute
  '/unit/': typeof AppUnitIndexRoute
  '/stock-positioning/': typeof AppStockPositioningIndexRoute
  '/user/': typeof AppUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/define-password': typeof AppDefinePasswordRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/category/edit': typeof AppCategoryEditRoute
  '/category/new': typeof AppCategoryNewRoute
  '/department/edit': typeof AppDepartmentEditRoute
  '/department/new': typeof AppDepartmentNewRoute
  '/product-brand/edit': typeof AppProductBrandEditRoute
  '/product-brand/new': typeof AppProductBrandNewRoute
  '/purchase/edit': typeof AppPurchaseEditRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/stock-location/edit': typeof AppStockLocationEditRoute
  '/stock-location/new': typeof AppStockLocationNewRoute
  '/stock-requisition/edit': typeof AppStockRequisitionEditRoute
  '/stock-requisition/new': typeof AppStockRequisitionNewRoute
  '/unit/edit': typeof AppUnitEditRoute
  '/unit/new': typeof AppUnitNewRoute
  '/user/edit': typeof AppUserEditRoute
  '/user/new': typeof AppUserNewRoute
  '/category': typeof AppCategoryIndexRoute
  '/department': typeof AppDepartmentIndexRoute
  '/product-brand': typeof AppProductBrandIndexRoute
  '/product': typeof AppProductIndexRoute
  '/purchase': typeof AppPurchaseIndexRoute
  '/user': typeof AppUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/define-password': typeof AppDefinePasswordRoute
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/category/edit': typeof AppCategoryEditRoute
  '/_app/category/new': typeof AppCategoryNewRoute
  '/_app/department/edit': typeof AppDepartmentEditRoute
  '/_app/department/new': typeof AppDepartmentNewRoute
  '/_app/product-brand/edit': typeof AppProductBrandEditRoute
  '/_app/product-brand/new': typeof AppProductBrandNewRoute
  '/_app/purchase/edit': typeof AppPurchaseEditRoute
  '/_app/purchase/new': typeof AppPurchaseNewRoute
  '/_app/stock-location/edit': typeof AppStockLocationEditRoute
  '/_app/stock-location/new': typeof AppStockLocationNewRoute
  '/_app/stock-requisition/edit': typeof AppStockRequisitionEditRoute
  '/_app/stock-requisition/new': typeof AppStockRequisitionNewRoute
  '/_app/unit/edit': typeof AppUnitEditRoute
  '/_app/unit/new': typeof AppUnitNewRoute
  '/_app/user/edit': typeof AppUserEditRoute
  '/_app/user/new': typeof AppUserNewRoute
  '/_app/category/': typeof AppCategoryIndexRoute
  '/_app/department/': typeof AppDepartmentIndexRoute
  '/_app/product-brand/': typeof AppProductBrandIndexRoute
  '/_app/product/': typeof AppProductIndexRoute
  '/_app/purchase/': typeof AppPurchaseIndexRoute
  '/_app/user/': typeof AppUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/define-password'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/unauthorized'
    | '/category/edit'
    | '/category/new'
    | '/department/edit'
    | '/department/new'
    | '/product-brand/edit'
    | '/product-brand/new'
    | '/purchase/edit'
    | '/purchase/new'
    | '/stock-location/edit'
    | '/stock-location/new'
    | '/stock-requisition/edit'
    | '/stock-requisition/new'
    | '/unit/edit'
    | '/unit/new'
    | '/user/edit'
    | '/user/new'
    | '/category/'
    | '/department/'
    | '/product-brand/'
    | '/product/'
    | '/purchase/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/define-password'
    | '/check-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/unauthorized'
    | '/category/edit'
    | '/category/new'
    | '/department/edit'
    | '/department/new'
    | '/product-brand/edit'
    | '/product-brand/new'
    | '/purchase/edit'
    | '/purchase/new'
    | '/stock-location/edit'
    | '/stock-location/new'
    | '/stock-requisition/edit'
    | '/stock-requisition/new'
    | '/unit/edit'
    | '/unit/new'
    | '/user/edit'
    | '/user/new'
    | '/category'
    | '/department'
    | '/product-brand'
    | '/product'
    | '/purchase'
    | '/user'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/define-password'
    | '/_auth/check-email'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/unauthorized'
    | '/_app/'
    | '/_app/category/edit'
    | '/_app/category/new'
    | '/_app/department/edit'
    | '/_app/department/new'
    | '/_app/product-brand/edit'
    | '/_app/product-brand/new'
    | '/_app/purchase/edit'
    | '/_app/purchase/new'
    | '/_app/stock-location/edit'
    | '/_app/stock-location/new'
    | '/_app/stock-requisition/edit'
    | '/_app/stock-requisition/new'
    | '/_app/unit/edit'
    | '/_app/unit/new'
    | '/_app/user/edit'
    | '/_app/user/new'
    | '/_app/category/'
    | '/_app/department/'
    | '/_app/product-brand/'
    | '/_app/product/'
    | '/_app/purchase/'
    | '/_app/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/define-password': {
      id: '/_app/define-password'
      path: '/define-password'
      fullPath: '/define-password'
      preLoaderRoute: typeof AppDefinePasswordRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/user/': {
      id: '/_app/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/unit/': {
      id: '/_app/unit/'
      path: '/unit'
      fullPath: '/unit/'
      preLoaderRoute: typeof AppUnitIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-requisition/': {
      id: '/_app/stock-requisition/'
      path: '/stock-requisition'
      fullPath: '/stock-requisition/'
      preLoaderRoute: typeof AppStockRequisitionIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-location/': {
      id: '/_app/stock-location/'
      path: '/stock-location'
      fullPath: '/stock-location/'
      preLoaderRoute: typeof AppStockLocationIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-positioning/': {
      id: '/_app/stock-positioning/'
      path: '/stock-positioning'
      fullPath: '/stock-positioning/'
      preLoaderRoute: typeof AppStockPositioningIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/purchase/': {
      id: '/_app/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof AppPurchaseIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product/': {
      id: '/_app/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof AppProductIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product-brand/': {
      id: '/_app/product-brand/'
      path: '/product-brand'
      fullPath: '/product-brand/'
      preLoaderRoute: typeof AppProductBrandIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/department/': {
      id: '/_app/department/'
      path: '/department'
      fullPath: '/department/'
      preLoaderRoute: typeof AppDepartmentIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/category/': {
      id: '/_app/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof AppCategoryIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/user/new': {
      id: '/_app/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof AppUserNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/user/edit': {
      id: '/_app/user/edit'
      path: '/user/edit'
      fullPath: '/user/edit'
      preLoaderRoute: typeof AppUserEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/unit/new': {
      id: '/_app/unit/new'
      path: '/unit/new'
      fullPath: '/unit/new'
      preLoaderRoute: typeof AppUnitNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/unit/edit': {
      id: '/_app/unit/edit'
      path: '/unit/edit'
      fullPath: '/unit/edit'
      preLoaderRoute: typeof AppUnitEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-requisition/new': {
      id: '/_app/stock-requisition/new'
      path: '/stock-requisition/new'
      fullPath: '/stock-requisition/new'
      preLoaderRoute: typeof AppStockRequisitionNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-requisition/edit': {
      id: '/_app/stock-requisition/edit'
      path: '/stock-requisition/edit'
      fullPath: '/stock-requisition/edit'
      preLoaderRoute: typeof AppStockRequisitionEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-location/new': {
      id: '/_app/stock-location/new'
      path: '/stock-location/new'
      fullPath: '/stock-location/new'
      preLoaderRoute: typeof AppStockLocationNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock-location/edit': {
      id: '/_app/stock-location/edit'
      path: '/stock-location/edit'
      fullPath: '/stock-location/edit'
      preLoaderRoute: typeof AppStockLocationEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/purchase/new': {
      id: '/_app/purchase/new'
      path: '/purchase/new'
      fullPath: '/purchase/new'
      preLoaderRoute: typeof AppPurchaseNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/purchase/edit': {
      id: '/_app/purchase/edit'
      path: '/purchase/edit'
      fullPath: '/purchase/edit'
      preLoaderRoute: typeof AppPurchaseEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product-brand/new': {
      id: '/_app/product-brand/new'
      path: '/product-brand/new'
      fullPath: '/product-brand/new'
      preLoaderRoute: typeof AppProductBrandNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/product-brand/edit': {
      id: '/_app/product-brand/edit'
      path: '/product-brand/edit'
      fullPath: '/product-brand/edit'
      preLoaderRoute: typeof AppProductBrandEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/department/new': {
      id: '/_app/department/new'
      path: '/department/new'
      fullPath: '/department/new'
      preLoaderRoute: typeof AppDepartmentNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/department/edit': {
      id: '/_app/department/edit'
      path: '/department/edit'
      fullPath: '/department/edit'
      preLoaderRoute: typeof AppDepartmentEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/category/new': {
      id: '/_app/category/new'
      path: '/category/new'
      fullPath: '/category/new'
      preLoaderRoute: typeof AppCategoryNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/category/edit': {
      id: '/_app/category/edit'
      path: '/category/edit'
      fullPath: '/category/edit'
      preLoaderRoute: typeof AppCategoryEditRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppDefinePasswordRoute: typeof AppDefinePasswordRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoryEditRoute: typeof AppCategoryEditRoute
  AppCategoryNewRoute: typeof AppCategoryNewRoute
  AppDepartmentEditRoute: typeof AppDepartmentEditRoute
  AppDepartmentNewRoute: typeof AppDepartmentNewRoute
  AppProductBrandEditRoute: typeof AppProductBrandEditRoute
  AppProductBrandNewRoute: typeof AppProductBrandNewRoute
  AppPurchaseEditRoute: typeof AppPurchaseEditRoute
  AppPurchaseNewRoute: typeof AppPurchaseNewRoute
  AppStockLocationEditRoute: typeof AppStockLocationEditRoute
  AppStockLocationNewRoute: typeof AppStockLocationNewRoute
  AppStockRequisitionEditRoute: typeof AppStockRequisitionEditRoute
  AppStockRequisitionNewRoute: typeof AppStockRequisitionNewRoute
  AppUnitEditRoute: typeof AppUnitEditRoute
  AppUnitNewRoute: typeof AppUnitNewRoute
  AppUserEditRoute: typeof AppUserEditRoute
  AppUserNewRoute: typeof AppUserNewRoute
  AppCategoryIndexRoute: typeof AppCategoryIndexRoute
  AppDepartmentIndexRoute: typeof AppDepartmentIndexRoute
  AppProductBrandIndexRoute: typeof AppProductBrandIndexRoute
  AppProductIndexRoute: typeof AppProductIndexRoute
  AppPurchaseIndexRoute: typeof AppPurchaseIndexRoute
  AppStockLocationIndexRoute: typeof AppStockLocationIndexRoute
  AppStockRequisitionIndexRoute: typeof AppStockRequisitionIndexRoute
  AppUnitIndexRoute: typeof AppUnitIndexRoute
  AppStockPositioningIndexRoute: typeof AppStockPositioningIndexRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDefinePasswordRoute: AppDefinePasswordRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoryEditRoute: AppCategoryEditRoute,
  AppCategoryNewRoute: AppCategoryNewRoute,
  AppDepartmentEditRoute: AppDepartmentEditRoute,
  AppDepartmentNewRoute: AppDepartmentNewRoute,
  AppProductBrandEditRoute: AppProductBrandEditRoute,
  AppProductBrandNewRoute: AppProductBrandNewRoute,
  AppPurchaseEditRoute: AppPurchaseEditRoute,
  AppPurchaseNewRoute: AppPurchaseNewRoute,
  AppStockLocationEditRoute: AppStockLocationEditRoute,
  AppStockLocationNewRoute: AppStockLocationNewRoute,
  AppStockRequisitionEditRoute: AppStockRequisitionEditRoute,
  AppStockRequisitionNewRoute: AppStockRequisitionNewRoute,
  AppUnitEditRoute: AppUnitEditRoute,
  AppUnitNewRoute: AppUnitNewRoute,
  AppUserEditRoute: AppUserEditRoute,
  AppUserNewRoute: AppUserNewRoute,
  AppCategoryIndexRoute: AppCategoryIndexRoute,
  AppDepartmentIndexRoute: AppDepartmentIndexRoute,
  AppProductBrandIndexRoute: AppProductBrandIndexRoute,
  AppProductIndexRoute: AppProductIndexRoute,
  AppPurchaseIndexRoute: AppPurchaseIndexRoute,
  AppStockLocationIndexRoute: AppStockLocationIndexRoute,
  AppStockRequisitionIndexRoute: AppStockRequisitionIndexRoute,
  AppUnitIndexRoute: AppUnitIndexRoute,
  AppStockPositioningIndexRoute: AppStockPositioningIndexRoute,
  AppUserIndexRoute: AppUserIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
